version: "3.8"

services:
  librarydb: 
    build: ./DockerFiles/db
    image: anesbhd/librarydb
    container_name: librarydb
    ports:
      - "3306:3306"
    volumes:
      - librarydbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin12
    networks:
      - app-network

  libraryapp: 
    build:
      context: ./DockerFiles/app
    image: anesbhd/libraryapp
    container_name: libraryapp
    networks:
      - app-network

  libraryweb: 
    build: ./DockerFiles/web
    image: anesbhd/libraryweb
    container_name: libraryweb
    ports:
      - "80:80"
    depends_on:
      - libraryapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  librarydbdata:
